### ISSUE TITLE
Request for Data Dictionary for ASA24 and DHQ3 Example Datasets in `dietaryindex`

### ISSUE THREAD

**Issue by dlemas** [jamesjiadazhan/dietaryindex#313]
Thank you for developing the `dietaryindex` package—it has been incredibly valuable for dietary research and analysis!

We are currently working to format our dietary data from **Food Processor**. I did not see a specific data format for **ESHA** and would like to structure my data similarly to the ASA24 and DHQ3 datasets. To ensure proper use and alignment with our own data, I was wondering if you have a **data dictionary** for the example datasets provided in the package. Specifically, it would be great to have detailed documentation on the following:

## Dataset Structure
- **Column names, data types, and descriptions** for both ASA24 and DHQ3 example datasets.
- **Clarification on mandatory vs. optional columns** required for specific functions in the package.

## Expected Input Format
- Guidance on how the provided datasets align with `dietaryindex` functions.
- Any **preprocessing steps** required to prepare external datasets (e.g., from ESHA/Food Processor) in a compatible format.

Having a comprehensive data dictionary will help ensure that:
- Data is prepared consistently and correctly for analysis.
- The provided functions can be used effectively with external datasets.
- Users new to the package can better understand the requirements and structure for input data.

Thank you for considering this request! Please let me know if additional details or examples from my own dataset would be helpful.

**Comment by jamesjiadazhan** [comment]
Hi there,

Thanks for your interest in dietaryindex!

I would encourage you to explore the generic function of dietary index, like HEI2015(), instead of making your dataset like ASA24. Those generic functions have very specific required data input and can provide the same output as those functions for ASA24 and DHQ3.

For details, see here:
- https://jamesjiadazhan.github.io/dietaryindex_manual/reference/index.html
